# Generated by Django 4.1.1 on 2022-11-30 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'verbose_name_plural': 'アカウント'},
        ),
    ]
